apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EWXdPREUwTkRVMU9Wb1hEVE13TURZd05qRTBORFUxT1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTFdaCitIRXlXUHRoY3EyaTdrL3NuYU1SL3dZUGdneTAxdXplTE0xTlM3RTR2ZVFzSzhwNzBseEJLcDk4Q1MwT1FKVHYKdkVPUEZZT2VZbHRWbXFDZ0I0QVlyQ3RpbWVLOUVkOVl0b3NuTWMvTlB5TU14UkZFZi9Ga0FENXVoVGZyOEdxcQp2allRQThxcWVBUllDN3NHdmZPUXp3ZHJxOVJHQk1vTlFzS0FlYmFRY1M1djNWQzR6RlY5SUV5RFUyR0VRdjJxCkt6K0prQ1dwdkJjaVFSQlhreDl4L3loamdQUU9YYW1wUWxxZERMYzlMWlpDZ3RPU3RtcFFvS0thakFkd2NXcWkKdnkyd1liT1QvM2lUTk9RSDU4N3pVQmI0bXQwY2RXdFlQdWl1SllBcFJPS3kwUytDZE5oNVByc0plV2UwTjVCYgpNZms2L1YveUpNSEJsM1FldEJNQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJMHVWV21vQlUwamZ2c1V4YzlNSlNlUHFxNHgKK2JCb2EzenVNTmJoWmUwVVlNYmo1Ky83TDQ5Y29CaDA4T2ROVEdRVnhIdWYzZ0ZuY1ZxMGlPWXl1Y0hESkZlSgpCYVd0MDJONC9zdlozL1NDYVFlZFIvVUVETnllaXVSN1c0YVh0dGJvY3pvODVDeFo4cXlPMTlTNUtabCtTbUtICnlaVktiTGNkQmVTSjFrUmZFaStTNEs0QTJzYWtNcDRtWG5lczNTU0tBZDJreXJpNkVSeWZ1a2Q5Yk14QTY1MVkKNmZGZ3FuaitWbGtuOEkyeVV1OFZkV20zb3dvYVZtRkQ0a2VtQ1d6U0JDUkVqZHYxeEd4bStRNUJBV0VlTnVxVwpzZ2tvRDNCeDBZdisrd2N0YXlZQ1pqZ0lid1hSSWxuL04zbWUwbnZOSnRrc0l3clRoTkZTRThkY1hSUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://CE8D6A493D4DBFC0A50BECE2A8558A25.yl4.ap-south-1.eks.amazonaws.com
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    namespace: default
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - eks
      - get-token
      - --cluster-name
      - sateks
      command: aws
      env: null
